build.gradle
lib/src/main/java/io/token/TransferTokenBuilder.java

proto version bump, moved transfer purpose

proto bump

---

build.gradle
lib/src/main/java/io/token/Account.java
lib/src/main/java/io/token/AccountAsync.java

expose account's isLocked property in java sdk

expose isLocked in account proto

---

samples/src/main/java/io/token/sample/CreateMemberSample.java

folks keep asking about it. let's mention it sooner

createMember sample += use default recovery rule

---

android/src/main/AndroidManifest.xml
android/src/main/java/io/token/browser/TokenBrowserActivity.java
android/src/main/java/io/token/browser/TokenBrowserFactory.java
lib/src/main/java/io/token/Member.java
lib/src/main/java/io/token/MemberAsync.java
lib/src/main/java/io/token/TransferTokenBuilder.java
lib/src/main/java/io/token/browser/Browser.java
lib/src/main/java/io/token/browser/BrowserClosedException.java
lib/src/main/java/io/token/rpc/Client.java
lib/src/main/java/io/token/util/Util.java

Implement initiateAccountLinking with browser instance.
Can test using https://github.com/tokenio/android-lib-tmp/tree/testing.

Pl 1049.linking

---

android/src/main/AndroidManifest.xml
android/src/main/java/io/token/browser/MessengerClient.java
android/src/main/java/io/token/browser/TokenBrowserActivity.java
android/src/main/java/io/token/browser/TokenBrowserFactory.java
android/src/main/java/io/token/browser/TokenBrowserService.java
android/src/main/res/values/strings.xml
build.gradle
lib/src/main/java/io/token/Member.java
lib/src/main/java/io/token/MemberAsync.java
lib/src/main/java/io/token/browser/Browser.java
lib/src/main/java/io/token/browser/BrowserClosedException.java
lib/src/main/java/io/token/browser/BrowserFactory.java
lib/src/main/java/io/token/exceptions/BankAuthorizationRequiredException.java
lib/src/main/java/io/token/rpc/Client.java
lib/src/main/java/io/token/util/Util.java

1. Provide Browser API interface (Browser.java) and Android implementation, which will open a WebView in a new Activity to display the pages.
2. linkAccounts method which takes in browser, directs the browser through bank pages, and completes entire linking process, returning linked accounts.
Usage example with Android SDK:
``` java
BrowserFactory browserFactory = new TokenBrowserFactory(MainActivity.this);
BankAuthorization auth = sdk.linkAccounts(bankInfo, browserFactory);
```

Browser API

---

build.gradle
lib/src/main/java/io/token/Member.java
lib/src/main/java/io/token/MemberAsync.java
lib/src/main/java/io/token/TokenIO.java
lib/src/main/java/io/token/TokenIOAsync.java
lib/src/main/java/io/token/rpc/Client.java
lib/src/main/java/io/token/util/Util.java

- Adds method linkAccounts(bankId, accessToken) in case the user doesn't want to use browser (For AMAIZ, who wants to use the sdk from the server side.)
- Change redirect url to webapp

Access token linking

---

build.gradle
lib/src/main/java/io/token/Member.java
lib/src/main/java/io/token/MemberAsync.java
lib/src/main/java/io/token/rpc/Client.java

gateway no longer uses memberId for either call

remove memberId from set/get receipt contact methods

---

android/src/main/java/io/token/browser/TokenBrowserActivity.java
build.gradle

This fixes the bug on @VKCR's phone.

use deprecated shouldOverrideUrlLoading syntax

---

build.gradle
lib/src/main/java/io/token/AccessTokenBuilder.java
lib/src/main/java/io/token/Member.java
lib/src/main/java/io/token/MemberAsync.java
lib/src/main/java/io/token/TokenIO.java
lib/src/main/java/io/token/TokenIOAsync.java
lib/src/main/java/io/token/TransferTokenBuilder.java
lib/src/main/java/io/token/exceptions/MemberNotFoundException.java
lib/src/main/java/io/token/rpc/UnauthenticatedClient.java
lib/src/main/java/io/token/util/Util.java

1 Update to the newest proto
2 Implement new realm logic in sdk
3 Update hash function

implment new realm logic in sdk

---

build.gradle
lib/src/main/java/io/token/Member.java
lib/src/main/java/io/token/MemberAsync.java
lib/src/main/java/io/token/TokenIO.java
lib/src/main/java/io/token/TokenIOAsync.java
lib/src/main/java/io/token/rpc/Client.java
lib/src/main/java/io/token/rpc/UnauthenticatedClient.java
lib/src/main/java/io/token/tokenrequest/TokenRequestResult.java

add get token request result and sign token request calls.

add get token request result and sign token request calls

---

build.gradle
lib/src/main/java/io/token/TokenIO.java
lib/src/main/java/io/token/TokenIOAsync.java
lib/src/main/java/io/token/rpc/UnauthenticatedClient.java

Optional arguments are not shown in the api. Add them back to the calls.

add missing arguments

---

build.gradle
lib/src/main/java/io/token/Member.java
lib/src/main/java/io/token/MemberAsync.java
lib/src/main/java/io/token/rpc/Client.java

Allows a partner to verify an affiliated TPP

RD-1024: Add VerifyAffiliate

---

samples/src/main/java/io/token/sample/RedeemAccessTokenSample.java

Add comments that serve as documentation code snippet anchor, so that we can change the code in between.

access token sample snippet anchor

---

build.gradle
lib/src/main/java/io/token/TokenIO.java
lib/src/main/java/io/token/TokenIOAsync.java
lib/src/main/java/io/token/TransferTokenBuilder.java
lib/src/main/java/io/token/rpc/UnauthenticatedClient.java

1. Remove setBankAuthorization from TransferTokenBuilder.
2. Remove notifyLinkAccounts and notifyLinkAccountsAndAddKey methods

RD-1279: remove bank authorization

---

build.gradle
lib/src/main/java/io/token/AccessTokenBuilder.java
lib/src/test/java/io/token/AccessTokenBuilderTest.java
samples/src/main/java/io/token/sample/CreateAndEndorseAccessTokenSample.java
samples/src/main/java/io/token/sample/ReplaceAccessTokenSample.java
samples/src/main/java/io/token/sample/StoreAndRetrieveTokenRequestSample.java
samples/src/test/java/io/token/sample/CancelAccessTokenSampleTest.java
samples/src/test/java/io/token/sample/CreateAndEndorseAccessTokenSampleTest.java
samples/src/test/java/io/token/sample/NotifySampleTest.java
samples/src/test/java/io/token/sample/RedeemAccessTokenSampleTest.java
samples/src/test/java/io/token/sample/ReplaceAccessTokenSampleTest.java
samples/src/test/java/io/token/sample/StoreAndRetrieveTokenRequestSampleTest.java

https://github.com/tokenio/slate/pull/332

RD-1366: remove wildcard access token resources

---

build.gradle

remove lib-util

---

build.gradle
lib/src/main/java/io/token/TokenIO.java
lib/src/main/java/io/token/TokenIOAsync.java
lib/src/main/java/io/token/rpc/UnauthenticatedClient.java

Only provider in the bank filter is useful in this call.

add get bank countries call

---

build.gradle
core/src/main/java/io/token/tokenrequest/TokenRequest.java
core/src/main/java/io/token/tokenrequest/TokenRequestState.java
core/src/main/java/io/token/util/Util.java
tpp/src/main/java/io/token/tpp/Member.java
tpp/src/main/java/io/token/tpp/TokenClient.java
tpp/src/main/java/io/token/tpp/tokenrequest/TokenRequestCallbackParameters.java
tpp/src/main/java/io/token/tpp/util/Util.java
user/src/main/java/io/token/user/Member.java

and fix TokenRequest state setter

RD-2057: add processTokenRequestCallback

---

build.gradle
core/src/main/java/io/token/TokenClient.java
tpp/src/main/java/io/token/tpp/TokenClient.java

"Option 2": add withFeatureCodes(String... featureCodes) to TokenClient builder.

RD-2121: add support for feature codes

---

build.gradle
core/src/main/java/io/token/Member.java
core/src/main/java/io/token/TokenClient.java
core/src/main/java/io/token/rpc/UnauthenticatedClient.java
core/src/main/java/io/token/util/Util.java
tpp-sample/src/main/java/io/token/sample/MemberMethodsSample.java
tpp-sample/src/test/java/io/token/sample/MemberMethodsSampleTest.java
user-sample/src/main/java/io/token/sample/CreateMemberSample.java
user-sample/src/main/java/io/token/sample/MemberMethodsSample.java
user-sample/src/test/java/io/token/sample/MemberMethodsSampleTest.java
user/src/main/java/io/token/user/Member.java

- Add MemberMethodsSample
- Add setDefaultAccount

RD-2208/2136: Normalize alias on add, remove

---

android/src/main/java/io/token/security/AKSCryptoEngine.java
android/src/main/java/io/token/security/AKSCryptoEngineFactory.java
build.gradle
core/src/main/java/io/token/Member.java
core/src/main/java/io/token/exceptions/InvalidSignatureException.java
core/src/main/java/io/token/rpc/Client.java
core/src/main/java/io/token/rpc/ErrorHandler.java
core/src/main/java/io/token/tokenrequest/TokenRequestResult.java
core/src/main/java/io/token/tokenrequest/TokenRequestState.java
tpp/src/main/java/io/token/tpp/exceptions/InvalidTokenRequestQuery.java
tpp/src/main/java/io/token/tpp/tokenrequest/TokenRequestCallback.java
tpp/src/main/java/io/token/tpp/tokenrequest/TokenRequestCallbackParameters.java
tpp/src/main/java/io/token/tpp/util/Util.java
user/src/main/java/io/token/user/AccessTokenBuilder.java
user/src/main/java/io/token/user/Member.java
user/src/main/java/io/token/user/PrepareTokenResult.java
user/src/main/java/io/token/user/TransferTokenBuilder.java
user/src/main/java/io/token/user/rpc/Client.java

Samples will be added in a separate PR.

RD-1407: add prepareToken, createToken, signTokenPayload

---

samples/src/test/java/io/token/sample/TestUtil.java
tpp-sample/src/test/java/io/token/sample/TestUtil.java
user-sample/src/test/java/io/token/sample/TestUtil.java

Fix the realm tests from https://github.com/tokenio/member/pull/245/files#diff-465be3250a74e2fbcba8d7b0fd90e620R88

fix the realm

---

build.gradle

revert the rpc update in https://github.com/tokenio/sdk-java/commit/2e3546abc7698fbada4ff6c462c0f25aba5655a3 since I break android sdk.

revert the rpc update

---

android/build.gradle
android/src/androidTest/java/io/token/android/AKSCryptoEngineTest.java
android/src/androidTest/java/io/token/android/LocaleTest.java
build.gradle

https://github.com/tokenio/lib-rpc/pull/105
https://github.com/tokenio/lib-proto/pull/360

bump rpc/proto version and add locale tests

---

build.gradle
user/src/main/java/io/token/user/Member.java
user/src/main/java/io/token/user/util/Util.java

error handling for bank linking.
Supports callback url like: "http://[webappUrl]?error=access_denied&...."

error handling in bank linking

---

RELEASE_NOTES.md
build.gradle
core/src/main/java/io/token/rpc/Client.java
core/src/main/java/io/token/tokenrequest/TokenRequest.java
gradle/wrapper/gradle-wrapper.properties
tpp/src/main/java/io/token/tpp/Member.java
tpp/src/main/java/io/token/tpp/rpc/Client.java
user/src/main/java/io/token/user/BulkTransferTokenBuilder.java
user/src/main/java/io/token/user/Member.java
user/src/main/java/io/token/user/rpc/Client.java

RD-3123: add bulk transfers

---

build.gradle
core/src/main/java/io/token/TokenClient.java
core/src/main/java/io/token/rpc/UnauthenticatedClient.java

It's breaking but it is only used in our Android project so it is fine.

update bank filters

---

RELEASE_NOTES.md

1) Changed 2.7.0 to 2.7.x
2) Added "Last Updated:" <date>

Updated release notes

---

android/src/main/java/io/token/security/AKSCryptoEngine.java

Do I need to bump the version? How?

RD-3764: implement createSigner(keyId) in android module

---

build.gradle

Bump proto to have EidasVerificationStatus along with KonsentusVerificationStatus.

RD-4603: bump proto

---

build.gradle
core/src/main/java/io/token/rpc/Client.java
tpp-sample/src/test/java/io/token/sample/EidasMethodsSampleTest.java
tpp/src/main/java/io/token/tpp/Member.java
tpp/src/main/java/io/token/tpp/rpc/Client.java

**Depends on:**
https://github.com/tokenio/lib-proto/pull/479
https://github.com/tokenio/gateway/pull/478

RD-4659: add getEidasInfo call

---

build.gradle
core/src/test/java/io/token/security/TokenCryptoEngineTest.java
tpp-sample/src/main/java/io/token/sample/EidasMethodsSample.java
tpp-sample/src/test/java/io/token/sample/EidasMethodsSampleTest.java
tpp-sample/src/test/java/io/token/tpp/util/UtilTest.java
tpp/src/main/java/io/token/tpp/TokenClient.java
tpp/src/main/java/io/token/tpp/exceptions/EidasRegistrationException.java
tpp/src/main/java/io/token/tpp/exceptions/EidasTimeoutException.java
tpp/src/main/java/io/token/tpp/security/EidasCryptoEngineFactory.java
tpp/src/main/java/io/token/tpp/security/EidasKeyStore.java
tpp/src/main/java/io/token/tpp/security/InMemoryEidasKeyStore.java
tpp/src/main/java/io/token/tpp/util/Util.java

Same as https://github.com/tokenio/sdk-java/pull/428 but with a util function to make a status check call until the status is not pending.

PLT-185: add createMemberWithEidas

---

build.gradle
core/src/main/java/io/token/tokenrequest/TokenRequest.java
tpp-sample/src/main/java/io/token/sample/StoreAndRetrieveTokenRequestSample.java
tpp-sample/src/test/java/io/token/sample/StoreAndRetrieveTokenRequestSampleTest.java

add samples with a preselected source account

PLT-969: use AccountIdentifier for the source account in token request

---

android/src/main/java/io/token/security/AKSCryptoEngine.java
build.gradle

Certificates could be null for some aliases.

PLT-1302: Fix AKSCryptoEngine

---

build.gradle
tpp-sample/src/main/java/io/token/sample/CreateMemberSample.java
tpp-sample/src/test/java/io/token/sample/CreateMemberSampleTest.java
user-sample/src/main/java/io/token/sample/CreateMemberSample.java
user-sample/src/main/java/io/token/sample/DeleteMemberSample.java
user-sample/src/test/java/io/token/sample/CreateMemberSampleTest.java
user-sample/src/test/java/io/token/sample/DeleteMemberSampleTest.java

Also, make DeleteMemberSampleTest to actually use DeletMemberSample

PLT-963: add CreateMemberSampleTest

---

build.gradle
tpp/src/main/java/io/token/tpp/Member.java
tpp/src/main/java/io/token/tpp/rpc/Client.java

To all initiateBankAuthorization and getBankAuthUrl methods. @gianluca-token I don't set any fallback value, as. this is gonna break if we set it to false.

PLT-1681 add consentUpdated param
