tokenio/sdk-java

- lib/src/main/java/io/token/MemberAsync.java
- lib/src/main/java/io/token/TokenIO.java
- lib/src/main/java/io/token/TokenIOAsync.java
- lib/src/main/java/io/token/rpc/UnauthenticatedClient.java
- samples/src/main/java/io/token/sample/MemberRecoverySample.java
- samples/src/test/java/io/token/sample/MemberRecoverySampleTest.java
sample code showing: setting up recovery for default recovery; recovering via default; setting up non-default; recovering via non-default
tweaked sdk behavior for verifyAlias; update SDK's cache of aliases if verifyAlias is succeeding.
creating an authorization needs member's lastHash; added an API to fetch member info and put its lastHash into an authorization.
> recovery samples. some api additions to get samples working

- RELEASE_NOTES.md
- build.gradle
- lib/src/main/java/io/token/TokenIO.java
- lib/src/main/java/io/token/TokenIOAsync.java
- lib/src/main/java/io/token/rpc/UnauthenticatedClient.java
- samples/src/main/java/io/token/sample/GetBalanceSample.java
- samples/src/main/java/io/token/sample/ProvisionDeviceSample.java
A developer had some reasonable questions about `TokenIO.login`, paraphrased: "...but there's no API to log out. What happens when a member is logged in? Is a session established? OK to login the same member several times?" Colin points out that we could change the "login" name to something less confusing.
> login name is confusing, so change it

- android/src/main/java/io/token/security/AKSCryptoEngine.java
- android/src/main/java/io/token/security/AKSSigner.java
- android/src/main/java/io/token/security/UserAuthenticationStore.java
- build.gradle
Lowers authentication time, catches another exception for authentication, replaces Signature CryptoObject with null. This is because next time the app makes an API call, the payload will change, and thus the Signature will be different, so we unfortunately can't rely on the CryptoObject.
> Fingerprint hybrid

- android/src/main/java/io/token/security/AKSSigner.java
- android/src/main/java/io/token/security/UserAuthenticationStore.java
- build.gradle
Since approveKey has multiple signatures, we can't force authentication on each signature. This makes us rely on the timeout (increased to 7 seconds to allow time for round trips), or on the client, who can expire the authentication using the UserAuthenticationStore.
> Don't expire the authentication after every signature

- samples/src/main/java/io/token/sample/RedeemAccessTokenSample.java
- samples/src/test/java/io/token/sample/RedeemAccessTokenSampleTest.java
so far, our redeem-access-token sample code shows how to use a token that has allAccounts. But if the token-grantor replaces that allAccounts with something more specific, e.g., edits the permissions in our iPhone app, that sample code fails to fetch any data. This new sample code shows how to use allAccounts if granted else use more-specific permissions.
> sample code += carefully use access token

- lib/src/main/java/io/token/MemberAsync.java
- lib/src/main/java/io/token/TransferTokenBuilder.java
- lib/src/main/java/io/token/browser/BrowserClosedException.java
- lib/src/main/java/io/token/rpc/Client.java
- lib/src/main/java/io/token/util/Util.java
Implements createTransferToken with browser.
Example Use: Suppose the user wants to make a payment from a CMA9 account, using an instance of browser to authenticate.
1. User adds browserFactory to TransferTokenBuilder using .setBrowserFactory.
2. User calls executeAsync on the TransferTokenBuilder; this will initiate the payment and direct the browser to authenticate.
Note: The user does not need to call createTransferToken a second time after authorization is obtained--this call is made automagically.
Concrete code to test this functionality can be found on the 'testing' branch of android-lib-temp.
> Pl 1049.payments

- samples/src/main/java/io/token/sample/StoreAndRetrieveTokenRequestSample.java
- samples/src/test/java/io/token/sample/StoreAndRetrieveTokenRequestSampleTest.java
access tokens normally have grantees, not payees?
email addresses w/capital letters bump into
my superstitions?
> change parts of samples that confuse me

- android/src/main/java/io/token/browser/TokenBrowserFactory.java
- build.gradle
In the previous design, we set the parent context of browser in tokeniobuilder, which will cause problem in old apis. add a method so that android app can change to the correct context for the older apis.
> add a method to change browser context in run time

- android/src/androidTest/java/io/token/android/AKSCryptoEngineTest.java
- android/src/main/java/io/token/security/AKSCryptoEngine.java
- android/src/main/java/io/token/security/AKSVerifier.java
- lib/src/main/java/io/token/security/CryptoEngine.java
- lib/src/main/java/io/token/security/InMemoryKeyStore.java
- lib/src/main/java/io/token/security/SecretKey.java
- lib/src/main/java/io/token/security/TokenCryptoEngine.java
- lib/src/main/java/io/token/security/UnsecuredFileSystemKeyStore.java
- lib/src/main/java/io/token/util/Clock.java
- lib/src/main/java/io/token/util/SystemTimeClock.java
- lib/src/test/java/io/token/security/InMemoryKeyStoreTest.java
- lib/src/test/java/io/token/security/KeyStoreTest.java
- lib/src/test/java/io/token/security/TokenCryptoEngineTest.java
- lib/src/test/java/io/token/security/UnsecuredFileSystemKeyStoreTest.java
- lib/src/test/java/io/token/util/TestClock.java
- lib/src/test/java/io/token/util/TimeUtil.java
- samples/src/test/java/io/token/sample/RedeemAccessTokenSampleTest.java
For pentesting, we enabled generating keys with expiration dates from the sdk. The KeyStore needs to know which keys are expired so it doesn't return a signer for an expired key, especially when a valid key exists that it could have returned instead. So I am adding clock to the KeyStore using it to filter out expired keys.
The Android crypto engine uses Android API's keystore. Newer versions of the API support key expiration nicely, but for older versions, I've needed to hack-ily encode the expiration date into the "alias" (the identifier for the keypair in the Android keystore). I've separated the logic so that we can just remove the chunks of code that support older versions of the API later on.
NOTE: I made a small change to AKSVerifier because it wasn't working when I tested it at …
> Pl 164.keystore

- build.gradle
- lib/src/main/java/io/token/TransferTokenBuilder.java
- lib/src/main/java/io/token/util/Util.java
The generated nonce's size will be 16~17 characters.
It might seem hacky to change the `generateNonce` call for the ref id field. If we end up having more and more fields with size limitation we can refactor the `generateNonce` call to have an input argument to indicate desired size. This solution works fine for now in my opinion.
> RD-306: Downsize generateNonce to fit in the ref id field

- build.gradle
- lib/src/main/java/io/token/Account.java
- lib/src/main/java/io/token/AccountAsync.java
The `Account` wrapper we have in the SDK doesn't expose all the information that the proto account object has, ie, `AccountFeatures`, `AccountTags`, etc. We would need to update `Account` every time we add something to the proto account object to keep them synced. I am thinking we should expose the proto account object in the `Account` wrapper, so in the wrapper interface we only have frequently/commonly used attributes.
A more immediate use case if that we need to update the merchant-proxy to support data access functionalities, which uses the Java SDK inside. We would need the Java SDK to expose the proto account object so that the merchant-proxy can access all the account information.
> Expose proto account objects

- android/build.gradle
- android/src/main/java/io/token/security/AKSSigner.java
- build.gradle
also changed order of repositories in android module cause in some cases build fails because gradle unable to find dependency in jcenter and doesn't try to search in goolge repo
> RD-491: updated dependencies

- android/src/main/java/io/token/browser/TokenBrowserActivity.java
- android/src/main/java/io/token/browser/TokenBrowserFactory.java
- android/src/main/java/io/token/browser/TokenBrowserService.java
- build.gradle
- lib/src/main/java/io/token/MemberAsync.java
Pressing the back button will now do the exact same thing as if the user manually closes the browser. (That is, close the activity and emit onComplete.) Is this the desired behavior @sibinlu ?
> TokenActivity emits onComplete on browser back button

- android/src/main/java/io/token/security/AKSCryptoEngine.java
- build.gradle
GetEntry time is not ignorable in aks key store. Re-order the code to avoid unnecessary codes.
> fix create signer latency

- RELEASE_NOTES.md
- build.gradle
- lib/src/main/java/io/token/TokenIO.java
- lib/src/main/java/io/token/TokenIOAsync.java
It has been more than 10 months since the methods were deprecated.
> remove deprecated login methods

- build.gradle
- lib/src/main/java/io/token/Member.java
- lib/src/main/java/io/token/MemberAsync.java
- lib/src/main/java/io/token/rpc/AuthenticationContext.java
- lib/src/main/java/io/token/rpc/Client.java
- lib/src/main/java/io/token/rpc/ClientAuthenticator.java
- lib/src/main/java/io/token/rpc/ClientAuthenticatorFactory.java
- lib/src/main/java/io/token/rpc/ClientFactory.java
- lib/src/main/java/io/token/rpc/ErrorHandler.java
- Allows users to supply security related metadata
- Makes AuthenticationContext stateless. Previously it used thread-local storage which can cause issues for Members that are shared across threads. The stateful nature of AuthenticationContext also allowed potential race conditions for asynchronous calls (eg first call sets keys level, begins connection, second call sets new key level, first call receives onMessage() event in authentication interceptor and reads incorrect key level). Now a new AuthenticationContext is created for each rpc call
> RD-1568: Security related metadata

- build.gradle
- core/src/main/java/io/token/tokenrequest/TokenRequest.java
When you call `.setFromAlias` on a transfer token request builder, for example, it should return a transfer token request builder, not the parent builder, so that you can subsequently call `.addDestination`, for example.
> improve token request builder

- android/build.gradle
- android/src/androidTest/java/io/token/android/AKSCryptoEngineTest.java
- android/src/main/java/io/token/security/AKSCryptoEngine.java
- android/src/main/java/io/token/security/AKSSigner.java
- android/src/main/java/io/token/security/AKSVerifier.java
- build.gradle
For some undocumented mystery reasons, Android team decides to mark KeyStore.getEntry as a service specific call. Therefore, whenever get entry is invoked on Android KeyStores, a ServiceSpecificException warning would be thrown.
other fixes:
1. fix android tests. it is not working.
2. clean up imports, in Android recommended order.
> fix ServiceSpecificException

- build.gradle
- tpp/src/main/java/io/token/tpp/Member.java
- user/src/main/java/io/token/user/Member.java
so that you can pass null in for List(TransferEndpoint) / List(TransferEndpoint) without matching multiple methods.
> add redeemToken convenience methods

- build.gradle
- user/src/main/java/io/token/user/Member.java
- user/src/main/java/io/token/user/TransferTokenBuilder.java
- user/src/main/java/io/token/user/rpc/Client.java
1. rename to createTransferTokenBuilder which makes more sense.
2. Add endpoint for createTransferTokenBuilder(TokenPayload)
3. From information is optional in TokenRequest and TokenPayload theoretically. If it doesn't present we can fill it with the member.
> update the endpoint for createTransferTokenBuilder

- android/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Not sure about bumping minor version. It looks like a pretty big jump in dependencies to me, so I won't be surprised that some our users would have problems with using this SDK (though it builds correctly to me without any changes).
If you think that we should just bump patch version, we can bump it instead of minor version.
P.S. @sibinlu com.github.dcendents:anrdoid-maven plugin is abandoned and won't work with gradle 5+ (see https://github.com/dcendents/android-maven-gradle-plugin) so it was replaced with https://github.com/sky-uk/gradle-maven-plugin.
> RD-798: upgrade gradle and java + dependencies + add keepalive-s

- build.gradle
- user/src/main/java/io/token/user/Member.java
1. Optional is not supported in Android API level 23
2. Mapper in Rxjava 2 don't support null.
So I decide to use an empty string for now
> use empty string instead of null in mapper

- android/src/main/java/io/token/security/AKSCryptoEngine.java
- build.gradle
key store is a share storage. We should not throw NullPointerException if we can not parse the member id from the key alias.
> fix unexpected null pointer exception

- .gitignore
- build.gradle
- core/src/main/java/io/token/exceptions/KeyNotFoundException.java
- core/src/main/java/io/token/rpc/ClientAuthenticator.java
- core/src/main/java/io/token/security/CryptoEngine.java
- core/src/main/java/io/token/security/InMemoryKeyStore.java
- core/src/main/java/io/token/security/KeyStore.java
- core/src/main/java/io/token/security/TokenCryptoEngine.java
- core/src/main/java/io/token/security/UnsecuredFileSystemKeyStore.java
- core/src/test/java/io/token/security/TokenCryptoEngineTest.java
- tpp-sample/src/main/java/io/token/sample/EidasMethodsSample.java
- tpp-sample/src/test/java/io/token/sample/EidasMethodsSampleTest.java
- tpp-sample/src/test/java/io/token/sample/TestUtil.java
- tpp/src/main/java/io/token/tpp/TokenClient.java
- tpp/src/main/java/io/token/tpp/rpc/UnauthenticatedClient.java
To make it work, I also had to 
1) add possibility to create keys for different crypto types in TokenCryptoEngine;
2) use a key of a requested level or higher (if no key can be found for the requested level) in ClientAuthenticator;
I also formalized exceptions thrown by KeyStore when a key cannot be found or expired, to better catch exception it ClientAuthenticator when looking for an existing key.
> PLT-109: add registerWithEidas call

- build.gradle
rpc logger to consider usage of new extension `hash` for fields in proto objects.
> bump rpc-lib

- android/build.gradle
- build.gradle
- core/build.gradle
- tpp/build.gradle
- user/build.gradle
1. Android java doc is not in plan. Should not block the build if broken.
2. add failOnVersionConflict to check all sdks don't have transitive conflicts. (For non-gradle users.)
3. bump versions.
> PLT-795: resolve dependencies
